// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddInventoryItem(arg1) {
  return window['go']['db']['DatabaseService']['AddInventoryItem'](arg1);
}

export function AddLogIssue(arg1) {
  return window['go']['db']['DatabaseService']['AddLogIssue'](arg1);
}

export function AddMechanic(arg1) {
  return window['go']['db']['DatabaseService']['AddMechanic'](arg1);
}

export function AddShip(arg1) {
  return window['go']['db']['DatabaseService']['AddShip'](arg1);
}

export function AddShipIssue(arg1) {
  return window['go']['db']['DatabaseService']['AddShipIssue'](arg1);
}

export function AddWorkOrderItems(arg1, arg2) {
  return window['go']['db']['DatabaseService']['AddWorkOrderItems'](arg1, arg2);
}

export function AssignMechanicToShip(arg1, arg2) {
  return window['go']['db']['DatabaseService']['AssignMechanicToShip'](arg1, arg2);
}

export function GetAllShipsLogReports() {
  return window['go']['db']['DatabaseService']['GetAllShipsLogReports']();
}

export function GetLogIssueReportByID(arg1) {
  return window['go']['db']['DatabaseService']['GetLogIssueReportByID'](arg1);
}

export function GetLogsIssues() {
  return window['go']['db']['DatabaseService']['GetLogsIssues']();
}

export function GetMechanics() {
  return window['go']['db']['DatabaseService']['GetMechanics']();
}

export function GetShipAssignments() {
  return window['go']['db']['DatabaseService']['GetShipAssignments']();
}

export function GetShipIssues() {
  return window['go']['db']['DatabaseService']['GetShipIssues']();
}

export function GetShipLogIssueReports(arg1) {
  return window['go']['db']['DatabaseService']['GetShipLogIssueReports'](arg1);
}

export function GetShips() {
  return window['go']['db']['DatabaseService']['GetShips']();
}

export function UpdateInventoryItem(arg1) {
  return window['go']['db']['DatabaseService']['UpdateInventoryItem'](arg1);
}
